### ISSUE TITLE
JSON Max Length error

### ISSUE THREAD

**Issue by jcummings** [mbegan/Duo-PSModule#8]
If the JSON you are retrieving exceeds the default 2MB Powershell limit, the functions that perform imports will fail.  I'm working on trying to create an alternate ConvertFrom_Json function that uses the .NET classes to allow you to specify a larger max-length

**Comment by mbegan** [comment]
Oy, i guess i lucked out when I was using this and never hit that limit.

How many of which object are you running over the 2MB limit on?

This API would benefit greatly from some pagination... might be worth sending feedback to your AE or CSM.

**Comment by jcummings** [comment]
I grabbed a ConvertFrom-JSON2 function that uses the .NET libraries but adds a MaxLength Param.  I added it to the top of the Duo.pm1 file and changed the try/catch to use it rather than Convert-FromJson.  Works beautifully.  The custom function is a match for match to the standard function with the exception of a MaxSize param.  I'll push to a new branch later to let you take a look.

**Comment by jcummings** [comment]
I pushed to a new remote branch with the fix.

___________________________________________
John Cummings
john@jcummings.net
304-633-9464
@jcummings1974

**Comment by sham0day** [comment]
I believe I'm running into the same issue.  I'm running duoGetUser command with over 16,000 users and it eventually errors out when attempting "$psobj = ConvertFrom-Json -InputObject $txt" on line 460 of Duo.psm1.  This worked with less users.  Any plans on pushing the fix?  Thanks for putting this together.  It's really useful.

**Comment by mbegan** [comment]
Hi @sham0day I am happy to merge a pull request.

@jcummings could you send a pull request through?

also to both of you as you are probably some of the larger paying customers for Duo, i would highly encourage you to reach out to Duo and let them know that this is an issue.  A client consuming an ever growing response object without an programmatic mechanism to chunk the data (ie pagination) is a problem waiting to happen, at some point Duo will need to address this gap.

**Comment by sham0day** [comment]
Thank you!  I've reached out to Duo.  I'll let you know what I hear back.

**Comment by sham0day** [comment]
Probably won't get a change from Duo any time soon.  Was this pull request sent?  Thanks!

**Comment by mbegan** [comment]
I never saw a PR but I did find a ConvertFrom-Json2 function from someone else though.

[ConvertFrom-Json2](https://www.powershellgallery.com/packages/PSJira/1.2.4.104/Content/Functions%5CConvertFrom-Json2.ps1)

I'm not going to incorporate it into this module but you should be able to have it as a stand along function and add a argument to use one versus the other or just do a try/catch like @jcummings did.

I don't have access to a Duo org to test anymore and they weren't keen on giving me a freebie. (their free orgs don't allow interaction with the admin api).

I'll also add a shameless plug here, if you want to use a security product that takes their API seriously you should look at Okta.

**Comment by Manimi-Chart** [comment]
Duo is now not only supporting pagination but will be enforcing it on all API calls starting March 15th of this year: https://help.duo.com/s/article/4744?language=en_US
Are there any plans to incorporate the new calls before the cutoff date?

**Comment by mbegan** [comment]
I haven't had access to a Duo org for a few years so my ability to dev/test pagination is limited.  I am happy to accept a pull request if anyone is interested in working it out.

**Comment by rjrbytes** [comment]
I think I have pagination done (and by extension, resolution of this Json error), thought it could certainly use some more testing. Since I've got very limited experience with git, I haven't figured out how to submit this update to this project. I'm going to tackle that on Monday (or over the weekend if I find time). I did note some degree of mismatch between the bypass code function behavior and what duo has actually documented, but since I don't use those calls I didn't spend much time on it.

**Comment by rjrbytes** [comment]
Okay ... after much fumbling with git, I've submitted the pull request that has support for the -limit parameter (with an alias for pagesize since that's more accurate in my opinion).  want to give it a try @Manimi-Chart and let me know if I broke something? @mbegan  thanks for your original code and hopefully I didn't break it with my changes. If you have questions/comments/concerns, let me know.

**Comment by rjrbytes** [comment]
Forgot to tag @jcummings ... this should fix the Json issue from what I can tell as well since the paged results shouldn't have individual pages that are too large, and if they are, you can reduce the page size. I did not put any throttling into the code or tweaks to catch "try again later", but I expect to need to handle throttling at a later date.

**Comment by mbegan** [comment]
Thanks @rjrbytes for PR #21

**Comment by Manimi-Chart** [comment]
Thanks @rjrbytes!  I have tested using the -limit parameter and the results are accurate.
